// Core System Permissions
export const corePermissions = [
  // Dashboard
  {
    name: "Home",
    displayName: "Home",
    slug: "home",
    group: "dashboard",
    groupOrder: 1,
    order: 1,
  },
  {
    name: "Admin Dashboard",
    displayName: "Admin Dashboard",
    slug: "admin.dashboard",
    group: "dashboard",
    groupOrder: 1,
    order: 2,
  },

  // Module Permissions - Core
  {
    name: "Admin Module",
    displayName: "Admin Module",
    slug: "admin.module",
    group: "module",
    groupOrder: 2,
    order: 1,
  },
  {
    name: "User Module",
    displayName: "User Module",
    slug: "user.module",
    group: "module",
    groupOrder: 2,
    order: 2,
  },
  {
    name: "Role & Permission Module",
    displayName: "Role & Permission Module",
    slug: "role.permission.module",
    group: "module",
    groupOrder: 2,
    order: 3,
  },
  {
    name: "Profile Module",
    displayName: "Profile Module",
    slug: "profile.module",
    group: "module",
    groupOrder: 2,
    order: 4,
  },
];

// Admin CRUD Permissions
export const adminCrudPermissions = [
  {
    name: "Admin View",
    displayName: "Admin View",
    slug: "admin.view",
    group: "admin",
    groupOrder: 3,
    order: 1,
  },
  {
    name: "Admin Create",
    displayName: "Admin Create",
    slug: "admin.create",
    group: "admin",
    groupOrder: 3,
    order: 2,
  },
  {
    name: "Admin Update",
    displayName: "Admin Update",
    slug: "admin.update",
    group: "admin",
    groupOrder: 3,
    order: 3,
  },
  {
    name: "Admin Delete",
    displayName: "Admin Delete",
    slug: "admin.delete",
    group: "admin",
    groupOrder: 3,
    order: 4,
  },
  {
    name: "Admin Status",
    displayName: "Admin Status",
    slug: "admin.status",
    group: "admin",
    groupOrder: 3,
    order: 5,
  },
  {
    name: "Admin Restore",
    displayName: "Admin Restore",
    slug: "admin.restore",
    group: "admin",
    groupOrder: 3,
    order: 6,
  },
  {
    name: "Admin Force Delete",
    displayName: "Admin Force Delete",
    slug: "admin.force-delete",
    group: "admin",
    groupOrder: 3,
    order: 7,
  },
];

// User CRUD Permissions
export const userCrudPermissions = [
  {
    name: "User View",
    displayName: "User View",
    slug: "user.view",
    group: "user",
    groupOrder: 4,
    order: 1,
  },
  {
    name: "User Create",
    displayName: "User Create",
    slug: "user.create",
    group: "user",
    groupOrder: 4,
    order: 2,
  },
  {
    name: "User Update",
    displayName: "User Update",
    slug: "user.update",
    group: "user",
    groupOrder: 4,
    order: 3,
  },
  {
    name: "User Delete",
    displayName: "User Delete",
    slug: "user.delete",
    group: "user",
    groupOrder: 4,
    order: 4,
  },
  {
    name: "User Status",
    displayName: "User Status",
    slug: "user.status",
    group: "user",
    groupOrder: 4,
    order: 5,
  },
  {
    name: "User Restore",
    displayName: "User Restore",
    slug: "user.restore",
    group: "user",
    groupOrder: 4,
    order: 6,
  },
  {
    name: "User Force Delete",
    displayName: "User Force Delete",
    slug: "user.force-delete",
    group: "user",
    groupOrder: 4,
    order: 7,
  },
];

// Role CRUD Permissions
export const roleCrudPermissions = [
  {
    name: "Role View",
    displayName: "Role View",
    slug: "role.view",
    group: "role",
    groupOrder: 5,
    order: 1,
  },
  {
    name: "Role Create",
    displayName: "Role Create",
    slug: "role.create",
    group: "role",
    groupOrder: 5,
    order: 2,
  },
  {
    name: "Role Update",
    displayName: "Role Update",
    slug: "role.update",
    group: "role",
    groupOrder: 5,
    order: 3,
  },
  {
    name: "Role Delete",
    displayName: "Role Delete",
    slug: "role.delete",
    group: "role",
    groupOrder: 5,
    order: 4,
  },
  {
    name: "Role Status",
    displayName: "Role Status",
    slug: "role.status",
    group: "role",
    groupOrder: 5,
    order: 5,
  },
  {
    name: "Role Restore",
    displayName: "Role Restore",
    slug: "role.restore",
    group: "role",
    groupOrder: 5,
    order: 6,
  },
  {
    name: "Role Force Delete",
    displayName: "Role Force Delete",
    slug: "role.force-delete",
    group: "role",
    groupOrder: 5,
    order: 7,
  },
];

// Permission CRUD Permissions
export const permissionCrudPermissions = [
  {
    name: "Permission View",
    displayName: "Permission View",
    slug: "permission.view",
    group: "permission",
    groupOrder: 6,
    order: 1,
  },
  {
    name: "Permission Create",
    displayName: "Permission Create",
    slug: "permission.create",
    group: "permission",
    groupOrder: 6,
    order: 2,
  },
  {
    name: "Permission Update",
    displayName: "Permission Update",
    slug: "permission.update",
    group: "permission",
    groupOrder: 6,
    order: 3,
  },
  {
    name: "Permission Delete",
    displayName: "Permission Delete",
    slug: "permission.delete",
    group: "permission",
    groupOrder: 6,
    order: 4,
  },
  {
    name: "Permission Status",
    displayName: "Permission Status",
    slug: "permission.status",
    group: "permission",
    groupOrder: 6,
    order: 5,
  },
  {
    name: "Permission Group Order",
    displayName: "Permission Group Order",
    slug: "permission.group.order",
    group: "permission",
    groupOrder: 6,
    order: 6,
  },
  {
    name: "Permission Order",
    displayName: "Permission Order",
    slug: "permission.order",
    group: "permission",
    groupOrder: 6,
    order: 7,
  },
  {
    name: "Permission Restore",
    displayName: "Permission Restore",
    slug: "permission.restore",
    group: "permission",
    groupOrder: 6,
    order: 8,
  },
  {
    name: "Permission Force Delete",
    displayName: "Permission Force Delete",
    slug: "permission.force-delete",
    group: "permission",
    groupOrder: 6,
    order: 9,
  },
];

// Profile Permissions
export const profilePermissions = [
  {
    name: "Profile View",
    displayName: "Profile View",
    slug: "profile.view",
    group: "profile",
    groupOrder: 9,
    order: 1,
  },
  {
    name: "Profile Update",
    displayName: "Profile Update",
    slug: "profile.update",
    group: "profile",
    groupOrder: 9,
    order: 2,
  },
];
